export const UPDATE_USER = 'UPDATE_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SHOW_LOADING = 'SHOW_LOADING';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const UPDATE_LOGGED_IN = 'UPDATE_LOGGED_IN';
export const LIST_PRODUCTS = 'LIST_PRODUCTS';